CREATE TABLE IF NOT EXISTS `batter` (
      `id` INTEGER NOT NULL PRIMARY KEY,
      `year` INTEGER,
      `name` text ,
      `team` text ,
      `bat` text ,
      `games` INTEGER ,
      `pa` INTEGER ,
      `ab` INTEGER ,
      `r` INTEGER ,
      `h` INTEGER ,
      `double` INTEGER ,
      `triple` INTEGER ,
      `hr` INTEGER ,
      `tb` INTEGER ,
      `rbi` INTEGER ,
      `so` INTEGER ,
      `bb` INTEGER ,
      `ibb` INTEGER ,
      `hbp` INTEGER ,
      `sh` INTEGER ,
      `sf` INTEGER ,
      `sb` INTEGER ,
      `cs` INTEGER ,
      `dp` INTEGER ,
      `ba` FLOAT ,
      `slg` FLOAT ,
      `obp` FLOAT,
      `create_date` DATETIME,
      `update_date` DATETIME
    );
